### ISSUE TITLE
Properties created by 'newproperty' command cannot be found by code.

### ISSUE THREAD

**Issue by davisvictorns** [MatheusrdSantos/PatrimonyManager#4]
I tried the first one, not created (i guess) by 'newproperty' command and works.

**Comment by MatheusrdSantos** [comment]
@davisvictorns, I'll solve this issue. I think the problem is a blank space being inserted into the database when creating a new property.
For example, if you're trying to insert the code '123' the code inserted is ' 123'

**Comment by MatheusrdSantos** [comment]
Solved here ec082f106582b65abd894bf267b11e5ba37772fd
